### ISSUE TITLE
Publish API docs somehow

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#225]
I believe the compiler's build would publish the scala-xml docs to [scala-lang.org/api](https://www.scala-lang.org/api/current/scala-xml/scala/xml/index.html).  

Now that the scala-xml dependency was ripped out of the compiler, it probably won't any longer.

I guess we could just migrate to github-pages or something.

**Comment by SethTisue** [comment]
> It would be better if this were on the scala-lang.org domain, rather than exposing scala.github.io

hmm, I don't know, maybe using scala.github.io is okay, actually. @fsalvi opinion?

> Git does a good job with compression, but it grows the compressed size of the repo from 2M to 5M

doesn't bother me, 5M is still small, and my guess is that as more versions are added, the size won't grow very fast since the additions will be so similar to the other files.

if the repo eventually gets too big, fsvo "too big", I think we could deal it with it then. (unlike on the main branches, on the gh-pages branch we can `git filter-branch` to our heart's content)

**Comment by fsalvi** [comment]
Well, there's already that:
https://www.scala-lang.org/api/2.12.8/scala-xml/scala/xml/

**Comment by ashawley** [comment]
Yes, the compiler used to publish the docs for scala-xml to scala-lang.org, but that won't be the case going forward.

**Comment by ashawley** [comment]
Ok, we will go with publishing scala-xml docs on scala.github.io.  It works for me.
