### ISSUE TITLE
Cannot stop XMLEventReader thread with Thread.sleep present (or v large file)

### ISSUE THREAD

**Issue by fancellu** [scala/scala-xml#24]
https://gist.github.com/fancellu/780d7c3dab1a8309f561

I'm trying to pull in some XML events, and stop after a few. 

Blocks on ProducerConsumerIterator.produce

If I take out the Thread.sleep, it works fine. 

Any idea why? Is this a known "feature" ?

Also, on a big (4GB) xml file, er.stop doesn't even stop it, seems to run to end of file

This isn't really what I want out of streaming.

Any help would be appreciated.

Thanks.

**Comment by ashawley** [comment]
I'm not able to verify this problem in a unit test.  Nothing has changed in the `XMLEventReader` since, and maybe something changed in Java, Scala or the standard library, but probably not much.  This test uses an infinite character stream as the source.

```scala
  @Test
  def largeSourceTest = {
    val src = new Source {
      val str = "<x><y z=''/>9</x>\n"
      lazy val elChars: Stream[Char] = str.toList.toStream #::: elChars
      protected val iter = elChars.toIterator
    }
    val reader = new XMLEventReader(src)
    reader.take(100)
    reader.stop
    src.close
  }
```

I even tried running it against a source of an actual 1G file , but I couldn't reproduce the issue.
