### ISSUE TITLE
Please publish to Maven Central for Dotty 0.27

### ISSUE THREAD

**Issue by Sciss** [scala/scala-xml#446]

**Comment by SethTisue** [comment]
@ashawley ? if you're otherwise occupied, I can do it

**Comment by SethTisue** [comment]
https://github.com/scala/scala-xml/releases/tag/v2.0.0-M2

**Comment by SethTisue** [comment]
staging repositories released, artifacts should be on their way to Maven Central

**Comment by SethTisue** [comment]
@Sciss let us know if the artifacts are actually usable :-)

**Comment by Sciss** [comment]
thanks, yes it seems to work

**Comment by Sciss** [comment]
Hmmm. I am seeing a strange problem in a library that uses a library that uses scala-xml. sbt collapses with

```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/hhrutz/Documents/devel/ScalaCollider/"), "scalacollider"):
[error]    org.scala-lang.modules:scala-xml _0.27, _2.13
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-xml
[error]         at scala.sys.package$.error(package.scala:30)
```
I don't really understand where that comes from. Could it be that the maven artifact somehow has some _2.13 information in it? I have currently no explanation why this error would come up. Checking the dependency trees there is no reference at all to scala-xml_2.13 for my dotty versions.

**Comment by SethTisue** [comment]
historically there have been weird problems with scala-xml because the 2.11 and 2.12 compilers depended on it. that dependency no longer exists in 2.13. is it a strictly 2.13/Dotty-only project?

it seems likely to be an sbt issue (either with sbt itself, or just in your build in particular) and not likely to be that something went wrong with the publishing here

**Comment by Sciss** [comment]
1.3.13. is there something newer?

**Comment by Sciss** [comment]
the project is 2.12, 2.13, dotty

**Comment by Sciss** [comment]
hold on -- I used `dependencyTree` not `test:dependencyTree`. Seems a problem of ScalaTest

**Comment by SethTisue** [comment]
> 1.3.13. is there something newer?

there's 1.4.0-RC1, but I would suggest sticking with 1.3.13 for now

> historically people have had weird problems with scala-xml in their builds

see #195 and linked tickets — though it's only a guess, I don't know if it's relevant

**Comment by SethTisue** [comment]
oh hey maybe trying sbt 1.4.0-RC1 would help, actually — is this https://github.com/sbt/sbt/issues/5369 ?

**Comment by Sciss** [comment]
d'oh
```
[info]   +-org.scalatest:scalatest_0.27:3.2.2
[info]     +-ch.epfl.lamp:dotty-library_0.27:0.27.0-RC1 [S]
[info]     +-org.scalatest:scalatest-core_0.27:3.2.2
[info]     | +-ch.epfl.lamp:dotty-library_0.27:0.27.0-RC1 [S]
[info]     | +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
```
I'm a bit confused now. Can dotty refer to Scala 2.13 libraries now? Is this advised or not?

**Comment by SethTisue** [comment]
Dotty can use Scala 2 libraries, that has worked for several years now. (As long as the libraries don't have macros; scala-xml doesn't.)

But when there are multiple levels of dependencies involved, I'm less sure what the failure modes are.

It makes sense that the Dotty build of ScalaTest would depend on a Scala 2 build of scala-xml, since there was no Dotty build of scala-xml until recently. So maybe you shouldn't be trying to use scala-xml_0.27:2.0.0-M2 at all. Maybe you should stick with scala-xml_2.13:1.2.0.
