### ISSUE TITLE
NamespaceBinding.buildString inproper handling of TopScope

### ISSUE THREAD

**Issue by muntis** [scala/scala-xml#45]
Starting with saca 2.11 NamespaceBinding.buildString uses private metohod doBuildString for namespace part generation. problem is that this method is not overrided in TopScope sub class. This generates unnecessary artifacts in form of empty (xmlns="") when constructing xml:

      def pretty(xml: Node) = new scala.xml.PrettyPrinter(200, 2).format(xml)
      val xx = <soapenv:Envelope xmlns:soapenv="aaa">
        <soapenv:Header xmlns:wsa="ssss">
        </soapenv:Header>
        <soapenv:Body><body xmlns:soapenv="aaa"></body></soapenv:Body>
      </soapenv:Envelope>
      println(pretty(xx))

Results in: 

    <soapenv:Envelope xmlns:soapenv="aaa" xmlns="">
      <soapenv:Header xmlns:wsa="ssss"> </soapenv:Header>
      <soapenv:Body>
        <body xmlns:soapenv="aaa"></body>
      </soapenv:Body>
    </soapenv:Envelope>

In this example problem can be fixed by setting pscope=TopScope for PrettyPrinter, but it does not help if xml is build from multiple parts.

    def pretty(xml: Node) = new scala.xml.PrettyPrinter(200, 2).format(xml, TopScope)
    val body = <body xmlns:soapenv="aaa"></body>
    val xx = <soapenv:Envelope xmlns:soapenv="aaa">
        <soapenv:Header xmlns:wsa="ssss">
        </soapenv:Header>
        <soapenv:Body>{body}</soapenv:Body>
        <soapenv:Body><body xmlns:soapenv="aaa"></body></soapenv:Body>
      </soapenv:Envelope>
    println(pretty(xx))

Results in: 

    <soapenv:Envelope xmlns:soapenv="aaa">
      <soapenv:Header xmlns:wsa="ssss"> </soapenv:Header>
      <soapenv:Body>
        <body xmlns:soapenv="aaa" xmlns=""></body>
      </soapenv:Body>
      <soapenv:Body>
        <body xmlns:soapenv="aaa"></body>
      </soapenv:Body>
    </soapenv:Envelope>

Sugested solution:

    override def buildString(sb: StringBuilder, stop: NamespaceBinding) {
      NamespaceBinding.doBuildString(shadowRedefined(stop), sb, stop)
    }

    object NamespaceBinding{
      def doBuildString(b: NamespaceBinding, sb: StringBuilder, stop: NamespaceBinding) {
        if ((this == null) || (this eq stop)) return // contains?

        sb append " xmlns%s=\"%s\"".format(
          (if (b.prefix != null) ":" + b.prefix else ""),
          (if (b.uri != null) b.uri else "")
        )
        b.parent match {
          case binding: NamespaceBinding => doBuildString(binding, sb, stop)
          case TopScope =>
        }
      }
    }

Or just change visibility of doBuildString and override it properly in TopScope like it's done with buildString methods

**Comment by ashawley** [comment]
The other option is adding `TopScope` as one of the sentinel values checked so that the function is prematurely exited and the blank namespace attribute is never built.

This is a strange bug. It is only complicated by the `null`-value problem.  This is similar to issue #28 that I ran across.  At some point, `null` was allowed and supported as a namespace binding throughout scala-xml.  Later, `null` was abandoned -- in favor of the `TopScope` construct.  Evidence the constructor for `Elem` which alludes to this transition from null to TopScope:

```
scala> scala.xml.Elem("x", "foo", scala.xml.Null, null, true)
java.lang.IllegalArgumentException: scope is null, use scala.xml.TopScope for empty scope
```
This bug has nothing to do with the `PrettyPrinter`.  Even the standard XML `toString` method is broken.  I'll try to add a slightly simpler test case, and then the fix using `TopScope`.

**Comment by biswanaths** [comment]
Thanks Aaron. Closing this one.
