### ISSUE TITLE
More information for potential Maintainers ? 

### ISSUE THREAD

**Issue by biswanaths** [scala/scala-xml#60]
Hey,

Can anybody please update the front-page with a e-mail address to reach( I really doubt anybody looking at issues or pull requests)  for whoever is interested to maintain this project ? Also it would be good if you provide some more information regarding what it entails maintaining this project.

Thanks.

**Comment by adriaanm** [comment]
Hi, welcome! Maintaining this project would entail responding to issues like this one, reviewing and merging PRs, and cutting releases. Eventually, you'd delegate this to others who join you :-) We've already set up the infrastructure so that you can perform all these tasks from your browser. For example, when you cut a tag here, a release will be staged and the Scala core team can promote it to Maven (contact [someone to coordinate with](https://github.com/scala/scala#get-in-touch). You'd also be expected to be somewhat aware of the scheduling of milestones over at scala/scala, so that you can focus on flushing PRs here and releasing in time for a main Scala release. 

PS: @mentioning me will result in a message at the top of my inbox.

**Comment by biswanaths** [comment]
Thanks @adriaanm 

I would like to maintain this project. Please let me know if you need any other information from me. 

Thanks.

**Comment by adriaanm** [comment]
Great, thank you! I'll take a look at your PR after the long weekend, and add you to the owners team on github.

**Comment by SethTisue** [comment]
@biswanaths it appears that @adriaanm sent you an invitation for https://github.com/orgs/scala/teams/community-maintainers, but you haven't responded to it?

**Comment by biswanaths** [comment]
@SethTisue  Done. Thanks for reminding me.

**Comment by SethTisue** [comment]
welcome!

**Comment by SethTisue** [comment]
would you like twitter.com/scala_lang to tweet the news? if you're on Twitter, we can retweet a tweet of your own. else, suggest a tweet text?

**Comment by biswanaths** [comment]
Yes, please do tweet it. My twitter handle is @biswanaths . 

On a side note will it get me free beers at bar.

**Comment by SethTisue** [comment]
https://twitter.com/scala_lang/status/624282958179004417

glad to hear you have external motivation :-)

**Comment by SethTisue** [comment]
a final piece of this is in https://github.com/scala/scala-xml/pull/80
