### ISSUE TITLE
community: open issues here for any significant old issue from JIRA

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#62]
today I closed all open XML tickets in the Scala JIRA: 9047, 8834, 7796, 7726, 7395, 7311, 7282, 6800, 6741, 6341, 5775, 5133, 5132, 5131, 5101, 4865, 4836, 4543, 4529, 4528, 4520, 4303, 4296, 4286, 4267, 4050, 3881, 3689, 3573, 3527, 3336, 3334, 3286, 3246, 3062, 2725, 1787, 1654

many of these ought to become issues here in this repo on GitHub. interested community members are invited to open new issues for them here, with links in both directions

**Comment by biswanaths** [comment]
Thanks @SethTisue  for the help. 
I will go through the issues and start creating them here.

**Comment by biswanaths** [comment]
I was searching if there was a migration story for issues for libraries. At least scala-parser-combinator is also have to deal with the same issue[1]. Let me see if there is any easier way to migrate JIRA to github. At least, description + linking(and back to github) to JIRA should be good enough.

[1]. https://github.com/scala/scala-parser-combinators/issues/61

**Comment by SethTisue** [comment]
scala-swing, too. if you could find a solution, that'd be great.

**Comment by biswanaths** [comment]
This hack of the script( https://gist.github.com/biswanaths/23b13af64ef8b93af562)  can do 
1. Create github issue given a jira issue.
2. Will create the description in the github issue as same as jira issue.
3. Create a link to jira issue in the github issue. 
4. Create a comment in jira issue pointint to github issue. 

It does not migrate comments or any other useful information. Please see 
1. https://github.com/biswanaths/scala_jira_gh/issues  , issue which are migrated from JIRA
2. https://issues.scala-lang.org/browse/TEST-14 , for a sample of comment which will get applied to individual jira cases. For the test run all the back link to github were added to Test-14.

Please let me know, if community has any concerns or suggestions.

**Comment by nikhilsinha** [comment]
Is anyone working on this?  I'm new to Scala, but if no one else has picked this up, I'd like to give it a try.

**Comment by mbeckerle** [comment]
I migrated several:

Original tickets are:
https://issues.scala-lang.org/browse/SI-7796 - XMLEventReader does not handle ' properly
https://issues.scala-lang.org/browse/SI-3527 - XML ConstructingParser too aggressive trimming whitespace around character references
Note: This one says fixed in Scala 2.11.7 - https://issues.scala-lang.org/browse/SI-3368 - Preserve CDATA sections, don't convert them to generic Text nodes.
https://issues.scala-lang.org/browse/SI-4303 - PrettyPrinter strips newlines from text in nodes, even pcdata
https://issues.scala-lang.org/browse/SI-4543 - PrettyPrinter removes newlines

The new issues are:

https://github.com/scala/scala-xml/issues/72
https://github.com/scala/scala-xml/issues/73
https://github.com/scala/scala-xml/issues/75
https://github.com/scala/scala-xml/issues/76
https://github.com/scala/scala-xml/issues/77

The above are the issues as they appear now at github scala-xml community.

Note that https://github.com/scala/scala-xml/issues/74, corresponding to https://issues.scala-lang.org/browse/SI-3368, was created, but both issues are closed as this was resolved before the migration of scala-xml to github.

**Comment by SethTisue** [comment]
I'll make this a README addition instead.

**Comment by SethTisue** [comment]
remaining unmigrated issues:

* [ ] https://github.com/scala/bug/issues/1654
* [ ] https://github.com/scala/bug/issues/1787
* [ ] https://github.com/scala/bug/issues/2725
* [ ] https://github.com/scala/bug/issues/3246
* [ ] https://github.com/scala/bug/issues/3286
* [ ] https://github.com/scala/bug/issues/3334
* [ ] https://github.com/scala/bug/issues/3336
* [ ] https://github.com/scala/bug/issues/3573
* [ ] https://github.com/scala/bug/issues/3881
* [ ] https://github.com/scala/bug/issues/4050
* [ ] https://github.com/scala/bug/issues/4267
* [ ] https://github.com/scala/bug/issues/4286
* [ ] https://github.com/scala/bug/issues/4296
* [ ] https://github.com/scala/bug/issues/4528
* [ ] https://github.com/scala/bug/issues/4529
* [ ] https://github.com/scala/bug/issues/4836
* [ ] https://github.com/scala/bug/issues/4865
* [ ] https://github.com/scala/bug/issues/5101
* [ ] https://github.com/scala/bug/issues/5131
* [ ] https://github.com/scala/bug/issues/5132
* [ ] https://github.com/scala/bug/issues/5133
* [ ] https://github.com/scala/bug/issues/5775
* [ ] https://github.com/scala/bug/issues/6800
* [ ] https://github.com/scala/bug/issues/7282
* [ ] https://github.com/scala/bug/issues/7395
* [ ] https://github.com/scala/bug/issues/8834

**Comment by SethTisue** [comment]
Note that GitHub now allows you to transfer issues between repos with the same organization. I can transfer and reopen any of the above upon request.
